### ISSUE TITLE
[BUG] Docker GPU branch not using GPU (upstream issue)

### ISSUE THREAD

**Issue by jxlarrea** [linuxserver/docker-piper#10]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The  `lscr.io/linuxserver/piper:gpu` image posted today does not use my RTX 4000 Ada GPU. It behaves exactly as the non-GPU branch.

### Expected Behavior

Should be using the GPU. 

### Steps To Reproduce

Run the container. 

### Environment

```markdown
- OS: Debian 12 LXC running on Proxmox.
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  piper:
    image: lscr.io/linuxserver/piper:gpu
    container_name: piper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    pull_policy: always
    environment:
      - PIPER_VOICE=en_US-lessac-medium
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    volumes:
      - /mnt/model/linuxserver-piper:/config
    ports:
      - 10200:10200
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started

[migrations] no migrations found

usermod: no changes

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    911

User GID:    911

───────────────────────────────────────

Linuxserver.io version: 1.4.0-ls7

Build-date: 2025-01-27T09:11:53+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

INFO:__main__:Ready

Connection to localhost (127.0.0.1) 10200 port [tcp/*] succeeded!

[ls.io-init] done.
```

**Comment by systemofapwne** [comment]
I see the same issue: I just switched to the GPU branch in hope, that it utilizes the GPU. Apparently, it doesn't. The official docs even do not state GPU support yet.
I would honestly appreciate GPU support.

**Comment by michnovka** [comment]
I can confirm the package does not use my GPU, despite the same config with faster-whisper works:

```yaml
  piper:
    image: lscr.io/linuxserver/piper:gpu
    container_name: piper
    environment:
      - PIPER_VOICE=en_US-lessac-high
    volumes:
      - ./piper/data:/config
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
                - compute
```
